services:
  car_01:
    build: ./gp_backend/cars
    container_name: car_01
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=01
    - MQTT_BROKER=mqtt
  car_02:
    build: ./gp_backend/cars
    container_name: car_02
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=02
    - MQTT_BROKER=mqtt
  car_03:
    build: ./gp_backend/cars
    container_name: car_03
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=03
    - MQTT_BROKER=mqtt
  car_04:
    build: ./gp_backend/cars
    container_name: car_04
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=04
    - MQTT_BROKER=mqtt
  car_05:
    build: ./gp_backend/cars
    container_name: car_05
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=05
    - MQTT_BROKER=mqtt
  car_06:
    build: ./gp_backend/cars
    container_name: car_06
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=06
    - MQTT_BROKER=mqtt
  car_07:
    build: ./gp_backend/cars
    container_name: car_07
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=07
    - MQTT_BROKER=mqtt
  car_08:
    build: ./gp_backend/cars
    container_name: car_08
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=08
    - MQTT_BROKER=mqtt
  car_09:
    build: ./gp_backend/cars
    container_name: car_09
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=09
    - MQTT_BROKER=mqtt
  car_10:
    build: ./gp_backend/cars
    container_name: car_10
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=10
    - MQTT_BROKER=mqtt
  car_11:
    build: ./gp_backend/cars
    container_name: car_11
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=11
    - MQTT_BROKER=mqtt
  car_12:
    build: ./gp_backend/cars
    container_name: car_12
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=12
    - MQTT_BROKER=mqtt
  car_13:
    build: ./gp_backend/cars
    container_name: car_13
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=13
    - MQTT_BROKER=mqtt
  car_14:
    build: ./gp_backend/cars
    container_name: car_14
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=14
    - MQTT_BROKER=mqtt
  car_15:
    build: ./gp_backend/cars
    container_name: car_15
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=15
    - MQTT_BROKER=mqtt
  car_16:
    build: ./gp_backend/cars
    container_name: car_16
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=16
    - MQTT_BROKER=mqtt
  car_17:
    build: ./gp_backend/cars
    container_name: car_17
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=17
    - MQTT_BROKER=mqtt
  car_18:
    build: ./gp_backend/cars
    container_name: car_18
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=18
    - MQTT_BROKER=mqtt
  car_19:
    build: ./gp_backend/cars
    container_name: car_19
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=19
    - MQTT_BROKER=mqtt
  car_20:
    build: ./gp_backend/cars
    container_name: car_20
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=20
    - MQTT_BROKER=mqtt
  car_21:
    build: ./gp_backend/cars
    container_name: car_21
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=21
    - MQTT_BROKER=mqtt
  car_22:
    build: ./gp_backend/cars
    container_name: car_22
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=22
    - MQTT_BROKER=mqtt
  car_23:
    build: ./gp_backend/cars
    container_name: car_23
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=23
    - MQTT_BROKER=mqtt
  car_24:
    build: ./gp_backend/cars
    container_name: car_24
    depends_on:
    - mqtt
    - ssvcp
    environment:
    - CAR_ID=24
    - MQTT_BROKER=mqtt
  isccp_01:
    build: ./gp_backend/SCCP
    container_name: isccp_01
    depends_on:
    - mqtt
    - ssacp_01
    - ssacp_02
    - ssacp_03
    - mongo
    environment:
    - ISCCP_ID=01
    - BROKER=mqtt
  isccp_02:
    build: ./gp_backend/SCCP
    container_name: isccp_02
    depends_on:
    - mqtt
    - ssacp_01
    - ssacp_02
    - ssacp_03
    - mongo
    environment:
    - ISCCP_ID=02
    - BROKER=mqtt
  isccp_03:
    build: ./gp_backend/SCCP
    container_name: isccp_03
    depends_on:
    - mqtt
    - ssacp_01
    - ssacp_02
    - ssacp_03
    - mongo
    environment:
    - ISCCP_ID=03
    - BROKER=mqtt
  isccp_04:
    build: ./gp_backend/SCCP
    container_name: isccp_04
    depends_on:
    - mqtt
    - ssacp_01
    - ssacp_02
    - ssacp_03
    - mongo
    environment:
    - ISCCP_ID=04
    - BROKER=mqtt
  isccp_05:
    build: ./gp_backend/SCCP
    container_name: isccp_05
    depends_on:
    - mqtt
    - ssacp_01
    - ssacp_02
    - ssacp_03
    - mongo
    environment:
    - ISCCP_ID=05
    - BROKER=mqtt
  isccp_06:
    build: ./gp_backend/SCCP
    container_name: isccp_06
    depends_on:
    - mqtt
    - ssacp_01
    - ssacp_02
    - ssacp_03
    - mongo
    environment:
    - ISCCP_ID=06
    - BROKER=mqtt
  isccp_07:
    build: ./gp_backend/SCCP
    container_name: isccp_07
    depends_on:
    - mqtt
    - ssacp_01
    - ssacp_02
    - ssacp_03
    - mongo
    environment:
    - ISCCP_ID=07
    - BROKER=mqtt
  isccp_08:
    build: ./gp_backend/SCCP
    container_name: isccp_08
    depends_on:
    - mqtt
    - ssacp_01
    - ssacp_02
    - ssacp_03
    - mongo
    environment:
    - ISCCP_ID=08
    - BROKER=mqtt
  isccp_09:
    build: ./gp_backend/SCCP
    container_name: isccp_09
    depends_on:
    - mqtt
    - ssacp_01
    - ssacp_02
    - ssacp_03
    - mongo
    environment:
    - ISCCP_ID=09
    - BROKER=mqtt
  isccp_10:
    build: ./gp_backend/SCCP
    container_name: isccp_10
    depends_on:
    - mqtt
    - ssacp_01
    - ssacp_02
    - ssacp_03
    - mongo
    environment:
    - ISCCP_ID=10
    - BROKER=mqtt
  isccp_11:
    build: ./gp_backend/SCCP
    container_name: isccp_11
    depends_on:
    - mqtt
    - ssacp_01
    - ssacp_02
    - ssacp_03
    - mongo
    environment:
    - ISCCP_ID=11
    - BROKER=mqtt
  isccp_12:
    build: ./gp_backend/SCCP
    container_name: isccp_12
    depends_on:
    - mqtt
    - ssacp_01
    - ssacp_02
    - ssacp_03
    - mongo
    environment:
    - ISCCP_ID=12
    - BROKER=mqtt
  isccp_13:
    build: ./gp_backend/SCCP
    container_name: isccp_13
    depends_on:
    - mqtt
    - ssacp_01
    - ssacp_02
    - ssacp_03
    - mongo
    environment:
    - ISCCP_ID=13
    - BROKER=mqtt
  isccp_14:
    build: ./gp_backend/SCCP
    container_name: isccp_14
    depends_on:
    - mqtt
    - ssacp_01
    - ssacp_02
    - ssacp_03
    - mongo
    environment:
    - ISCCP_ID=14
    - BROKER=mqtt
  isccp_15:
    build: ./gp_backend/SCCP
    container_name: isccp_15
    depends_on:
    - mqtt
    - ssacp_01
    - ssacp_02
    - ssacp_03
    - mongo
    environment:
    - ISCCP_ID=15
    - BROKER=mqtt
